owner: fontsource
repo: status

sites:
  - name: Website
    url: https://fontsource.org/docs/getting-started/introduction # Don't query index to save Algolia credits
  - name: 'API: Fontlist'
    url: https://api.fontsource.org/fontlist
  - name: 'API: V1 Single Font'
    url: https://api.fontsource.org/v1/fonts/abel

status-website:
  name: Fontsource Status
  cname: status.fontsource.org
  logoUrl: https://fontsource.org/apple-touch-icon.png
  favicon: https://fontsource.org/favicon-16x16.png
  introTitle: "**Fontsource** uptime monitor and status page."
  css: body{font-family:'Inter Variable',sans-serif}
  links:
    - rel: stylesheet
      href: https://cdn.jsdelivr.net/npm/@fontsource-variable/inter@5
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Main Website
      href: https://fontsource.org

commitMessages:
  commitAuthorName: "fontsource-bot"
  commitAuthorEmail: "83556432+fontsource-bot@users.noreply.github.com"

i18n:
  footer: ''
